### ISSUE TITLE
Try out schema.sql for initializing what schema to be used

### ISSUE THREAD

**Issue by reylibutan** [reylibutan/tabula-rasa#1]
Instead of using

`spring.datasource.url=jdbc:postgresql://localhost:5432/myDB?currentSchema=mySchema`

**Comment by VicCebedo** [comment]
unsa diay ni? unsai main focus aning spring boot? haha

**Comment by reylibutan** [comment]
nindot ang Spring Boot, more coding, less configuration. opinionated default configuration but customizable. Awa almost walay xml akong project except pom.xml ug logback.xml. Mostly Java configuration pud.

**Comment by VicCebedo** [comment]
unsa kalahian nyas spring mvc? hmmm murag parepareho raman sila except sa servlet context xml. hmm

**Comment by reylibutan** [comment]
lahi man jud ang purpose sa Spring boot, automatic configuration raman sya, so kinanglan jpun spring mvc, spring security, etc.

**Comment by VicCebedo** [comment]
ang nindot kat unon kanang play framework ba, pina-RESTful2x, basta pina webservice2x,di ko kebaw ana haha

**Comment by reylibutan** [comment]
amo, Play sad haha pero masteron sa ko ni ang Spring kay mao ni akong selling point ahahha.
so far nana gmay nangita ug Play pero mas dghan jpun Spring haha

**Comment by reylibutan** [comment]
Irrelevant.
