### ISSUE TITLE
Clarify folder i18n

### ISSUE THREAD

**Issue by accidentallyc** [reylibutan/tabula-rasa#2]
src/main/resources/i18n.

Please place a readme.md or something :P

**Comment by reylibutan** [comment]
Please elaborate on this issue. What do I need to clarify regarding that folder?

**Comment by accidentallyc** [comment]
Everything hahahaha

**Comment by accidentallyc** [comment]
Found it. @ application.properties
>>>
# Internationalization
spring.messages.basename=i18n/messages

**Comment by reylibutan** [comment]
i18n > stands for InternationalizatioN > I - then 18 letters in bettwen - N = i18n

inside `/.../i18n/`, you can see `messages_X.properties`

these message files contains the labels you use in your application in relation to the current locale.

`messages.properties` -> default file to load if no match is found
`messages_en.properties` -> file to load if locale is English (or en_US)
`messages_jp.properties` -> file to load if locale is Japanese

[Local Identifiers](https://msdn.microsoft.com/en-us/library/ms693062(v=vs.85).aspx)
